branch-defaults:
  master:
    environment: Couplechat-env-1
environment-defaults:
  Couplechat-env-1:
    branch: null
    repository: null
global:
  application_name: coupleChat
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
