version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/coupleChat
    steps:
      - checkout
      - run:
          name: Update Node.js
          command: |
            set +e
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
            source ~/.nvm/nvm.sh
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install v10.16.3
            nvm alias default v10.16.3
            nvm use v10.16.3
            node -v

            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV
      - run:
          name: Check current node version
          command: |
            node -v
      - run:
          name: Create google credential json file
          command: |
            touch ~/coupleChat/coupleChat.json
            echo "${GOOGLE_APPLICATION_JSON}" > ~/coupleChat/coupleChat.json
      - run:
          name: Show Current Branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Install NPM Dependencies
          command: |
            sudo npm install --unsafe-perm
      - run:
          name: Install awscli
          command: |
            sudo apt install python-pip python-dev
            sudo pip install awsebcli --upgrade
      - run:
          name: Create AWS credentials manually
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 600 ~/.aws/config
            echo "[profile eb-cli]" > ~/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - run:
          name: Deploy to env
          command: |
            eb deploy Couplechat-env-1
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - dev
                - master
